server:
  port: 8085

spring:
  application:
    name: user-service
  datasource:
    url: jdbc:postgresql://192.168.1.3:5432/postgres
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        default_schema: rcrs_user
        dialect: org.hibernate.dialect.PostgreSQLDialect
  liquibase:
    change-log: classpath:/db/changelog/db.changelog-master.yaml
    user: postgres
    password: postgres
    url: jdbc:postgresql://192.168.1.3:5432/postgres
    database-change-log-table: user_databasechangelog
    database-change-log-lock-table: user_databasechangeloglock
  kafka:
    bootstrap-servers: 192.168.1.3:29092
  security:
    enabled: true
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://192.168.1.3:8180/realms/master
          jwk-set-uri: http://192.168.1.3:8180/realms/master/protocol/openid-connect/certs

image:
  cdn:
    endpoint: "http://192.168.1.3:4566/images"
  thumbnails:
    sizes:
      sm: 128
      md: 512
      lg: 1024

springdoc:
  api-docs:
    path: /me/v3/api-docs
  swagger-ui:
    path: /me/swagger-ui.html

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    preferIpAddress: true

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: when_authorized