server:
  port: 8085

spring:
  application:
    name: user-service
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/postgres?currentSchema=rcrs_user}
    username: ${SPRING_DATASOURCE_USERNAME:postgres}
    password: ${SPRING_DATASOURCE_PASSWORD:postgres}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  liquibase:
    change-log: classpath:/db/changelog/db.changelog-master.yaml
    user: ${SPRING_LIQUIBASE_USER:postgres}
    password: ${SPRING_LIQUIBASE_PASSWORD:postgres}
    url: ${SPRING_LIQUIBASE_URL:jdbc:postgresql://localhost:5432/postgres}
  kafka:
    bootstrap-servers: ${SPRING_KAFKA_BOOTSTRAP_SERVERS:localhost:9092}

identity:
  events:
    topic: ${IDENTITY_EVENTS_TOPIC:identity.events}

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE:http://localhost:8761/eureka/}
  instance:
    preferIpAddress: true
