server:
  port: 8081

spring:
  application:
    name: metadata-read-service
  mongodb:
    uri: mongodb://localhost:27017/rcrs_catalog
  kafka:
    bootstrap-servers: localhost:9092
  security:
    enabled: true
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8180/realms/rcrs
      client:
        provider:
          keycloak:
            issuer-uri: http://localhost:8180/realms/rcrs
            user-name-attribute: preferred_username
        registration:
          keycloak:
            client-id: rcrs-app
            client-secret: xuTR1hmVfO5ERSNdgl23JpW3vKTrACk0ampYzmmW3XoGoaJtE8h18CweFsSONWYAC6S7IJbvu7na38odNMogSC
            scope: openid

cdn:
  images:
    endpoint: "http://images.localhost:4566"

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    preferIpAddress: true

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: when_authorized