server:
  port: 8081

spring:
  application:
    name: metadata-read-service
  mongodb:
    uri: ${SPRING_DATA_MONGODB_URI}
  kafka:
    bootstrap-servers: ${SPRING_KAFKA_BOOTSTRAP_SERVERS}
  security:
    enabled: true
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${OAUTH2_ISSUER_URI}
      client:
        provider:
          keycloak:
            issuer-uri: ${KEYCLOAK_ISSUER_URI}
            user-name-attribute: ${USERNAME_ATTRIBUTE}
        registration:
          keycloak:
            client-id: ${CLIENT_ID}
            client-secret: ${CLIENT_SECRET}
            scope: ${SCOPE}

cdn:
  images:
    endpoint: ${CDN_IMAGES_ENDPOINT}

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: when_authorized