server:
  port: 8081

spring:
  application:
    name: metadata-read-service
  mongodb:
    uri: ${SPRING_DATA_MONGODB_URI:mongodb://localhost:27017/rcrs_catalog}
  kafka:
    bootstrap-servers: ${SPRING_KAFKA_BOOTSTRAP_SERVERS:localhost:9092}

cdn:
  images:
    endpoint: ${CDN_IMAGES_ENDPOINT:http://images.localhost:4566}

logging:
  level:
    root: INFO

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE:http://localhost:8761/eureka/}
  instance:
    preferIpAddress: true
