changelogFile: liquibase-cassandra/db/changelog/db.changelog-master.yaml
driver: com.ing.data.cassandra.jdbc.CassandraDriver
url: jdbc:cassandra://localhost:9042/rcrs_catalog?localdatacenter=my-datacenter-1&compliancemode=Liquibase
log-level: DEBUG
username:
password: