server:
  port: 8083
spring:
  application:
    name: search-service
  kafka:
    bootstrap-servers: localhost:9092
    reindex:
      batch:
        size: 1000
  data:
    elasticsearch:
      url: localhost:9200

cdn:
  images:
    endpoint: "http://images.localhost:4566"

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    preferIpAddress: true

logging:
  level:
    root: info
