server:
  port: 8083
spring:
  application:
    name: search-service
  cloud:
    openfeign:
      client:
        config:
          default:
            connectTimeout: 5000
            readTimeout: 5000
  kafka:
    bootstrap-servers: ${SPRING_KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
    reindex:
      batch:
        size: 1000
  data:
    elasticsearch:
      url: ${SPRING_DATA_ELASTICSEARCH_URL:http://localhost:9200}

cdn:
  images:
    endpoint: ${CDN_IMAGES_ENDPOINT:http://images.localhost:4566}

feign:
  catalog-service:
    url: ${FEIGN_CATALOG-SERVICE_URL:http://localhost:8080}

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE:http://localhost:8761/eureka/}
  instance:
    preferIpAddress: true

logging:
  level:
    root: info
