server:
  port: 8083
spring:
  application:
    name: search-service
  kafka:
    bootstrap-servers: ${SPRING_KAFKA_BOOTSTRAP_SERVERS}
    reindex:
      batch:
        size: 1000
  elasticsearch:
    uris: ${SPRING_ELASTICSEARCH_URIS}

cdn:
  images:
    endpoint: ${CDN_IMAGES_ENDPOINT}

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE}
  instance:
    preferIpAddress: true

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: when_authorized
