spring:
  application:
    name: search-service
  cloud:
    openfeign:
      client:
        config:
          default:
            connectTimeout: 5000
            readTimeout: 5000
  kafka:
    reindex:
      batch:
        size: 1000
    consumer:
      bootstrap-servers: localhost:9092
      group-id: my-group
      properties:
        reactiveAutoCommit: true
    producer:
      bootstrap-servers: localhost:9092

cdn:
  images:
    endpoint: "http://images.localhost:4566"

feign:
  catalog-service.url: http://localhost:8080

elasticsearch:
  url:  http://localhost:9200

