server:
  port: 8083
spring:
  application:
    name: search-service
  cloud:
    openfeign:
      client:
        config:
          default:
            connectTimeout: 5000
            readTimeout: 5000
  kafka:
    bootstrap-servers: localhost:9092
    reindex:
      batch:
        size: 1000
  elasticsearch:
    url: localhost:9200

cdn:
  images:
    endpoint: "http://images.localhost:4566"

feign:
  catalog-service.url: http://localhost:8080

logging.level.root: info

