server:
  port: 8083
spring:
  application:
    name: search-service
  kafka:
    bootstrap-servers: ${SPRING_KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
    reindex:
      batch:
        size: 1000
  elasticsearch:
    uris: localhost:9200

cdn:
  images:
    endpoint: ${CDN_IMAGES_ENDPOINT:http://images.localhost:4566}

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE:http://localhost:8761/eureka/}
  instance:
    preferIpAddress: true
