spring.application.name=media-service
server.port=8081
thumbnail.sizes=64,300,640

spring.cloud.aws.credentials.access-key=test
spring.cloud.aws.credentials.secret-key=test
spring.cloud.aws.region.static=eu-west-1
spring.cloud.aws.endpoint= http://localhost.localstack.cloud:4566
spring.cloud.aws.s3.path-style-access-enabled= true


s3.image-bucket=images
s3.upload.bucket=rcrs-upload
s3.upload.signature-duration=24h
s3.upload.sqs.queue=rcrs-upload-queue

spring.liquibase.change-log=classpath:/db/changelog/db.changelog-master.yaml
spring.liquibase.user=postgres
spring.liquibase.password=postgres
spring.liquibase.default-schema=rcrs_upload
spring.liquibase.url=jdbc:postgresql://localhost:5432/postgres?currentSchema=rcrs_upload
spring.datasource.url=jdbc:postgresql://localhost:5432/postgres?currentSchema=rcrs_upload
spring.datasource.username=postgres
spring.datasource.password=postgres

spring.kafka.topic.in=${spring.application.name}-in
spring.kafka.topic.catalog-service=catalog-service-in
spring.kafka.consumer.bootstrap-servers=localhost:9092
spring.kafka.consumer.key-deserializer=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.consumer.value-deserializer=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.consumer.group-id=my-group
spring.kafka.consumer.properties.reactiveAutoCommit=true
spring.kafka.producer.bootstrap-servers=localhost:9092
spring.kafka.producer.key-deserializer=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.producer.value-deserializer=org.apache.kafka.common.serialization.StringDeserializer

logging.level.org.springframework.web=debug

