server:
  port: 8082

spring:
  application:
    name: media-service
  temporal:
    connection:
      target: 127.0.0.1:7233
    namespace: default
    workers:
      capacity:
        max-concurrent-workflow-task-pollers: 6
        max-concurrent-activity-task-pollers: 6
      rate-limits:
        max-worker-activities-per-second: 2
        max-task-queue-activities-per-second: 2
    workflow-cache:
      max-instances: 10
      max-threads: 10
    activities:
      validateImage:
        start-to-close-timeout: 10s
        retry:
          initial-interval: 1s
          backoff-coefficient: 2
          maximum-interval: 10s
          maximum-attempts: 3
      saveOriginalImage:
        start-to-close-timeout: 15s
        retry:
          initial-interval: 1s
          backoff-coefficient: 2
          maximum-interval: 15s
          maximum-attempts: 3
      saveThumbnail:
        start-to-close-timeout: 15s
        retry:
          initial-interval: 1s
          backoff-coefficient: 2
          maximum-interval: 15s
          maximum-attempts: 3
      validateAudio:
        start-to-close-timeout: 30s
        retry:
          initial-interval: 1s
          backoff-coefficient: 2
          maximum-interval: 15s
          maximum-attempts: 3
      probeAudioMetadata:
        start-to-close-timeout: 30s
        retry:
          initial-interval: 1s
          backoff-coefficient: 2
          maximum-interval: 15s
          maximum-attempts: 3
      saveOriginalAudioToS3:
        start-to-close-timeout: 1m
        retry:
          initial-interval: 1s
          backoff-coefficient: 2
          maximum-interval: 30s
          maximum-attempts: 3
      saveAudioRecord:
        start-to-close-timeout: 10s
        retry:
          initial-interval: 1s
          backoff-coefficient: 2
          maximum-interval: 10s
          maximum-attempts: 5
      normalizeAudio:
        start-to-close-timeout: 5m
        retry:
          initial-interval: 1s
          backoff-coefficient: 2
          maximum-interval: 30s
          maximum-attempts: 1
      transcodingStatus:
        start-to-close-timeout: 10s
        retry:
          initial-interval: 1s
          backoff-coefficient: 2
          maximum-interval: 10s
          maximum-attempts: 3
  liquibase:
    change-log: classpath:/db/changelog/db.changelog-master.yaml
    user: postgres
    password: postgres
    default-schema: rcrs_upload
    url: jdbc:postgresql://localhost:5432/postgres?currentSchema=rcrs_upload
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres?currentSchema=rcrs_upload
    username: postgres
    password: postgres
  kafka:
    bootstrap-servers: localhost:9092
  cloud:
    aws:
      credentials:
        access-key: test
        secret-key: test
      region:
        static: eu-west-1
      endpoint: http://localhost.localstack.cloud:4566
      s3:
        path-style-access-enabled: true

cdn:
  images:
    bucket: images
    thumbnails: 64,300,640
  audios:
    bucket: rcrs-audio
    bitrates: "128k", "192k", "320k"
  uploads:
    bucket: rcrs-upload
    signature-duration: 24h
    file-duration: 24h
    sqs:
      queue: rcrs-upload-queue

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    preferIpAddress: true

