server:
  port: 8082

spring:
  application:
    name: media-service
  temporal:
    connection:
      target: ${SPRING_TEMPORAL_CONNECTION_TARGET:127.0.0.1:7233}
    namespace: default
    workers:
      capacity:
        max-concurrent-workflow-task-pollers: 6
        max-concurrent-activity-task-pollers: 6
      rate-limits:
        max-worker-activities-per-second: 2
        max-task-queue-activities-per-second: 2
    workflow-cache:
      max-instances: 10
      max-threads: 10
    activities:
      validateImage:
        start-to-close-timeout: 10s
        retry:
          initial-interval: 1s
          backoff-coefficient: 2
          maximum-interval: 10s
          maximum-attempts: 3
      saveOriginalImage:
        start-to-close-timeout: 15s
        retry:
          initial-interval: 1s
          backoff-coefficient: 2
          maximum-interval: 15s
          maximum-attempts: 3
      saveThumbnail:
        start-to-close-timeout: 15s
        retry:
          initial-interval: 1s
          backoff-coefficient: 2
          maximum-interval: 15s
          maximum-attempts: 3
      validateAudio:
        start-to-close-timeout: 30s
        retry:
          initial-interval: 1s
          backoff-coefficient: 2
          maximum-interval: 15s
          maximum-attempts: 3
      probeAudioMetadata:
        start-to-close-timeout: 30s
        retry:
          initial-interval: 1s
          backoff-coefficient: 2
          maximum-interval: 15s
          maximum-attempts: 3
      saveOriginalAudioToS3:
        start-to-close-timeout: 1m
        retry:
          initial-interval: 1s
          backoff-coefficient: 2
          maximum-interval: 30s
          maximum-attempts: 3
      saveAudioRecord:
        start-to-close-timeout: 10s
        retry:
          initial-interval: 1s
          backoff-coefficient: 2
          maximum-interval: 10s
          maximum-attempts: 5
      normalizeAudio:
        start-to-close-timeout: 5m
        retry:
          initial-interval: 1s
          backoff-coefficient: 2
          maximum-interval: 30s
          maximum-attempts: 1
      transcodingStatus:
        start-to-close-timeout: 10s
        retry:
          initial-interval: 1s
          backoff-coefficient: 2
          maximum-interval: 10s
          maximum-attempts: 3
  liquibase:
    change-log: classpath:/db/changelog/db.changelog-master.yaml
    user: ${SPRING_LIQUIBASE_USER:postgres}
    password: ${SPRING_LIQUIBASE_PASSWORD:postgres}
    default-schema: rcrs_upload
    url: ${SPRING_LIQUIBASE_URL:jdbc:postgresql://localhost:5432/postgres?currentSchema=rcrs_upload}
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/postgres?currentSchema=rcrs_upload}
    username: ${SPRING_DATASOURCE_USERNAME:postgres}
    password: ${SPRING_DATASOURCE_PASSWORD:postgres}
  kafka:
    bootstrap-servers: ${SPRING_KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
  cloud:
    aws:
      credentials:
        access-key: ${SPRING_CLOUD_AWS_CREDENTIALS_ACCESS_KEY:test}
        secret-key: ${SPRING_CLOUD_AWS_CREDENTIALS_SECRET_KEY:test}
      region:
        static: ${SPRING_CLOUD_AWS_REGION_STATIC:eu-west-1}
      endpoint: ${SPRING_CLOUD_AWS_ENDPOINT:http://localhost.localstack.cloud:4566}
      s3:
        path-style-access-enabled: true

cdn:
  images:
    bucket: ${CDN_IMAGES_BUCKET:images}
    thumbnails: ${CDN_IMAGES_THUMBNAILS:64,300,640}
  audios:
    bucket: ${CDN_AUDIOS_BUCKET:rcrs-audio}
    bitrates: ${CDN_AUDIOS_BITRATES:"128k", "192k", "320k"}
  uploads:
    bucket: ${CDN_UPLOADS_BUCKET:rcrs-upload}
    signature-duration: ${CDN_UPLOADS_SIGNATURE_DURATION:24h}
    file-duration: ${CDN_UPLOADS_FILE_DURATION:24h}
    sqs:
      queue: ${CDN_UPLOADS_SQS_QUEUE:rcrs-upload-event-queue}

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE:http://localhost:8761/eureka/}
  instance:
    preferIpAddress: true

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: when_authorized