spring.application.name=media-service
server.port=8081
thumbnail.sizes=64,300,640

spring.cloud.aws.credentials.access-key=test
spring.cloud.aws.credentials.secret-key=test
spring.cloud.aws.region.static=eu-west-1
spring.cloud.aws.endpoint= http://localhost.localstack.cloud:4566
spring.cloud.aws.s3.path-style-access-enabled= true


s3.image-bucket=rcrs-images
s3.upload.bucket=rcrs-upload
s3.upload.signature-duration=24h
s3.upload.sqs.queue=rcrs-upload-queue

spring.liquibase.change-log=classpath:/db/changelog/db.changelog-master.yaml
spring.liquibase.user=postgres
spring.liquibase.password=postgres
spring.liquibase.default-schema=rcrs_upload
spring.liquibase.url=jdbc:postgresql://localhost:5432/postgres?currentSchema=rcrs_upload
spring.datasource.url=jdbc:postgresql://localhost:5432/postgres?currentSchema=rcrs_upload
spring.datasource.username=postgres
spring.datasource.password=postgres
