server:
  port: 8082

spring:
  application:
    name: workflow-service
  cloud:
    openfeign:
      client:
        config:
          default:
            connectTimeout: 5000
            readTimeout: 5000
  kafka:
    bootstrap-servers: localhost:9092
  temporal:
    connection:
      target: 127.0.0.1:7233
    workflow:

    workers:
        capacity:
          max-concurrent-workflow-task-pollers: 6
          max-concurrent-activity-task-pollers: 6
        rate-limits:
          max-worker-activities-per-second: 2
          max-task-queue-activities-per-second: 2
    workflow-cache:
      max-instances: 10
      max-threads: 10
    workersAutoDiscovery:
      packages: org.ultra.rcrs.workflow
    namespace: default
    activities:
      artist:
        start-to-close-timeout: 30s
        retry:
          initial-interval: 1s
          backoff-coefficient: 2
          maximum-interval: 30s
          maximum-attempts: 5
      album:
        start-to-close-timeout: 30s
        retry:
          initial-interval: 1s
          backoff-coefficient: 2
          maximum-interval: 30s
          maximum-attempts: 5
      track:
        start-to-close-timeout: 30s
        retry:
          initial-interval: 1s
          backoff-coefficient: 2
          maximum-interval: 30s
          maximum-attempts: 5
      audio:
        start-to-close-timeout: 30s
        retry:
          initial-interval: 1s
          backoff-coefficient: 2
          maximum-interval: 30s
          maximum-attempts: 5
      transcoding:
        start-to-close-timeout: 30s
        retry:
          initial-interval: 1s
          backoff-coefficient: 2
          maximum-interval: 30s
          maximum-attempts: 5
      purge:
        start-to-close-timeout: 1m
        retry:
          initial-interval: 1s
          backoff-coefficient: 2
          maximum-interval: 30s
          maximum-attempts: 3

feign:
  metadata-service:
    url: http://localhost:8080
  media-service:
    url: http://localhost:8081
  search-service:
    url: http://localhost:8083

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    preferIpAddress: true

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: when_authorized
