server:
  port: 8090

workflow:
  purge:
    cron: ${WORKFLOW_PURGE_CRON}

spring:
  application:
    name: workflow-service
  cloud:
    openfeign:
      client:
        config:
          default:
            connectTimeout: 5000
            readTimeout: 5000
  kafka:
    bootstrap-servers: ${SPRING_KAFKA_BOOTSTRAP_SERVERS}
  security:
    enabled: true
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${OAUTH2_ISSUER_URI}
      client:
        provider:
          keycloak:
            issuer-uri: ${KEYCLOAK_ISSUER_URI}
            user-name-attribute: ${USERNAME_ATTRIBUTE}
        registration:
          keycloak:
            client-id: ${CLIENT_ID}
            client-secret: ${CLIENT_SECRET}
            scope: ${SCOPE}
  temporal:
    connection:
      target: ${SPRING_TEMPORAL_CONNECTION_TARGET}
    workflow:

    workers:
      capacity:
        max-concurrent-workflow-task-pollers: 6
        max-concurrent-activity-task-pollers: 6
      rate-limits:
        max-worker-activities-per-second: 2
        max-task-queue-activities-per-second: 2
    workflow-cache:
      max-instances: 10
      max-threads: 10
    workersAutoDiscovery:
      packages: org.ultra.rcrs.workflow
    namespace: default
    activities:
      artist:
        start-to-close-timeout: 30s
        retry:
          initial-interval: 1s
          backoff-coefficient: 2
          maximum-interval: 30s
          maximum-attempts: 5
      album:
        start-to-close-timeout: 30s
        retry:
          initial-interval: 1s
          backoff-coefficient: 2
          maximum-interval: 30s
          maximum-attempts: 5
      track:
        start-to-close-timeout: 30s
        retry:
          initial-interval: 1s
          backoff-coefficient: 2
          maximum-interval: 30s
          maximum-attempts: 5
      audio:
        start-to-close-timeout: 30s
        retry:
          initial-interval: 1s
          backoff-coefficient: 2
          maximum-interval: 30s
          maximum-attempts: 5
      transcoding:
        start-to-close-timeout: 30s
        retry:
          initial-interval: 1s
          backoff-coefficient: 2
          maximum-interval: 30s
          maximum-attempts: 5
      purge:
        start-to-close-timeout: 1m
        retry:
          initial-interval: 1s
          backoff-coefficient: 2
          maximum-interval: 30s
          maximum-attempts: 3

feign:
  metadata-service:
    url: ${FEIGN_METADATA-SERVICE_URL}
  media-service:
    url: ${FEIGN_MEDIA-SERVICE_URL}
  search-service:
    url: ${FEIGN_SEARCH-SERVICE_URL}

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: when_authorized
