spring:
  application:
    name: catalog-service
  cassandra:
    keyspace-name: "rcrs"
    contact-points: "localhost:9042"
    local-datacenter: "datacenter-1"
  kafka:
    bootstrap-servers: localhost:9092
    process-topic: "entity-process-topic"

service:
  media-service:
    url: http://media-service:8080

logging:
  level:
    root: INFO


app:
  read:
    enabled: true
  write:
    enabled: true
