spring:
  application:
    name: catalog-service
  liquibase:
    change-log: classpath:/db/changelog/db.changelog-master.yaml
    user: postgres
    password: postgres
    url: jdbc:postgresql://localhost:5432/rcrs?currentSchema=rcrs_catalog
  r2dbc:
    username: postgres
    password: postgres
    url: r2dbc:postgresql://localhost:5432/rcrs?currentSchema=rcrs_catalog
  #cassandra:
    #keyspace-name: "rcrs_catalog"
    #contact-points: "localhost:9042"
    #local-datacenter: "my-datacenter-1"
    #schema-action: CREATE_IF_NOT_EXISTS
  kafka:
    bootstrap-servers: localhost:9092
    process-topic: "entity-process-topic"

s3:
  images:
    endpoint: "http://localhost:9444"

logging:
  level:
    root: INFO


app:
  read:
    enabled: true
  write:
    enabled: true
