server:
  port: 8080

spring:
  application:
    name: metadata-write-service
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        default_schema: rcrs_catalog
        dialect: org.hibernate.dialect.PostgreSQLDialect
  liquibase:
    change-log: classpath:/db/changelog/db.changelog-master.yaml
    user: postgres
    password: postgres
    url: jdbc:postgresql://localhost:5432/postgres
    database-change-log-table: metadata_databasechangelog
    database-change-log-lock-table: metadata_databasechangeloglock
  kafka:
    bootstrap-servers: localhost:9092
  security:
    workflow:
      client-id: workflow-service-client
    admin:
      client-id: rcrs-admin-panel
    enabled: true
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://192.168.1.3:8180/realms/master
          jwk-set-uri: http://192.168.1.3:8180/realms/master/protocol/openid-connect/certs

image:
  cdn:
    endpoint: "http://images.localhost:4566"
  thumbnails:
    sizes:
      sm: 128
      md: 512
      lg: 1024

springdoc:
  api-docs:
    path: /catalog/v3/api-docs
  swagger-ui:
    path: /catalog/swagger-ui.html

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    preferIpAddress: true

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: when_authorized
