server:
  port: 8080

spring:
  application:
    name: metadata-write-service
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        default_schema: ${SPRING_HIBERNATE_DEFAUT_SCHEMA}
        dialect: org.hibernate.dialect.PostgreSQLDialect
  liquibase:
    change-log: classpath:/db/changelog/db.changelog-master.yaml
    user: ${SPRING_LIQUIBASE_USER}
    password: ${SPRING_LIQUIBASE_PASSWORD}
    url: ${SPRING_LIQUIBASE_URL}
    database-change-log-table: metadata_databasechangelog
    database-change-log-lock-table: metadata_databasechangeloglock
  kafka:
    bootstrap-servers: ${SPRING_KAFKA_BOOTSTRAP_SERVERS}

cdn:
  images:
    endpoint: ${CDN_IMAGES_ENDPOINT}

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE}
  instance:
    preferIpAddress: true

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: when_authorized