server:
  port: 8080

spring:
  application:
    name: metadata-write-service
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        default_schema: rcrs_catalog
        dialect: org.hibernate.dialect.PostgreSQLDialect
  liquibase:
    change-log: classpath:/db/changelog/db.changelog-master.yaml
    user: postgres
    password: postgres
    url: jdbc:postgresql://localhost:5432/postgres
    database-change-log-table: metadata_databasechangelog
    database-change-log-lock-table: metadata_databasechangeloglock
  kafka:
    bootstrap-servers: localhost:9092
  security:
    enabled: true
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8180/realms/rcrs

cdn:
  images:
    endpoint: "http://images.localhost:4566"

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    preferIpAddress: true

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: when_authorized
