spring.application.name=upload-service
server.port=8082

feign.media-service.url=http://localhost:8081
feign.catalog-service.url=http://localhost:8080/api/v1

spring.cloud.openfeign.client.config.default.connectTimeout=5000
spring.cloud.openfeign.client.config.default.readTimeout=5000