version: '3.8'

services:
  mongodb:
    image: mongo:7
    container_name: mongodb
    ports:
      - "27017:27017"
    command: ["mongod", "--replSet", "rs0"]
    environment:
      MONGO_INITDB_DATABASE: rcrs_catalog
    volumes:
      - mongodb_data:/data/db
      - ./init-replica.sh:/docker-entrypoint-initdb.d/init-replica.sh
    restart: unless-stopped

volumes:
  mongodb_data:
